#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""②300面化: 既存と重複しない実在の市区を追加生成（事実ベースのみ）。
gen-area-articles.py の gen() テンプレートを再利用。冪等（既存slugはスキップ）。
"""
import json, os, importlib.util

ROOT = os.path.expanduser("~/projects/kin-kaitori-biyori")
SRC = os.path.join(ROOT, "scripts", "gen-area-articles.py")
ART = os.path.join(ROOT, "app/articles")
META = os.path.join(ROOT, "data/articles-metadata.json")

# gen-area-articles.py をモジュールとして読み込み（main()は__main__ガードで実行されない）
spec = importlib.util.spec_from_file_location("genarea", SRC)
genmod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(genmod)
gen = genmod.gen

# (slug, 市区名, 都道府県, region, hook短語, [主要エリア3], intro, [related既存/新slug])
AREAS2 = [
 # ===== 東京23区（未収録の区）=====
 ("chuo-tokyo-kin-kaitori","中央区","東京都","kanto","日本橋・銀座を擁する商都",
  ["日本橋","銀座","八重洲"],
  "中央区は日本橋・銀座という日本有数の商業地を抱え、老舗の宝飾店や買取専門店が集まるエリアです。本格的な金地金から高級ジュエリーまで、相場に近い高価買取が狙えます。",
  ["ginza-kin-kaitori","tokyo-kin-kaitori","kin-necklace-kaitori"]),
 ("bunkyo-kin-kaitori","文京区","東京都","kanto","東京大学を擁する文教地区",
  ["後楽園","本郷","茗荷谷"],
  "文京区は東京大学や後楽園を擁する落ち着いた文教地区です。住宅地が多く、相続や生前整理にともなう金製品の出張買取需要が高い地域です。",
  ["tokyo-kin-kaitori","kin-souzoku-baikyaku","ueno-kin-kaitori"]),
 ("taito-kin-kaitori","台東区","東京都","kanto","上野・浅草・御徒町の下町",
  ["浅草","上野","御徒町"],
  "台東区は貴金属問屋街の御徒町や、観光地の浅草・上野を抱える下町です。区内に金・ジュエリーの専門業者が集中し、相場に近い査定が期待できます。",
  ["okachimachi-kin-kaitori","ueno-kin-kaitori","kinka-ingot-kaitori"]),
 ("kita-tokyo-kin-kaitori","北区","東京都","kanto","赤羽・王子の城北エリア",
  ["赤羽","王子","田端"],
  "北区は赤羽・王子を中心とした城北の住宅・商業エリアです。赤羽駅周辺に買取チェーンが集まり、埼玉方面からの来店も多い地域です。",
  ["tokyo-kin-kaitori","kita-senju-kin-kaitori","kin-takaku-uru"]),
 ("arakawa-kin-kaitori","荒川区","東京都","kanto","日暮里・町屋の下町",
  ["日暮里","町屋","南千住"],
  "荒川区は日暮里繊維街や町屋を抱える下町で、生活密着型の買取店が点在します。城東エリアからアクセスしやすく、ジュエリーの売却に便利です。",
  ["tokyo-kin-kaitori","kita-senju-kin-kaitori","kin-necklace-kaitori"]),
 # ===== 東京 多摩地域 =====
 ("fuchu-tokyo-kin-kaitori","府中","東京都","kanto","大國魂神社と競馬場の多摩中核市",
  ["府中駅周辺","分倍河原","府中本町"],
  "府中市は大國魂神社や東京競馬場で知られる多摩の中核都市です。京王・JR沿線に商業施設が集まり、駅周辺で金製品の売却がしやすい環境です。",
  ["tokyo-kin-kaitori","tachikawa-kin-kaitori","hachioji-kin-kaitori"]),
 ("chofu-kin-kaitori","調布","東京都","kanto","映画の街・京王沿線の住宅都市",
  ["調布駅周辺","つつじヶ丘","仙川"],
  "調布市は映画スタジオで知られる京王線沿線の住宅都市です。新宿へのアクセスが良く、駅前の買取店や出張買取で気軽に金を売却できます。",
  ["tokyo-kin-kaitori","fuchu-tokyo-kin-kaitori","kichijoji-kin-kaitori"]),
 ("mitaka-kin-kaitori","三鷹","東京都","kanto","ジブリ美術館と井の頭の住宅地",
  ["三鷹駅周辺","下連雀","井の頭"],
  "三鷹市はジブリ美術館や井の頭公園に隣接する人気の住宅地です。吉祥寺にも近く、買い物ついでにジュエリーを査定に出しやすいエリアです。",
  ["kichijoji-kin-kaitori","tokyo-kin-kaitori","kin-bracelet-kaitori"]),
 ("hino-tokyo-kin-kaitori","日野","東京都","kanto","新選組ゆかりの多摩の都市",
  ["日野駅周辺","豊田","高幡不動"],
  "日野市は新選組ゆかりの地として知られる多摩南部の都市です。中央線・京王線沿線に住宅地が広がり、出張買取の需要が高い地域です。",
  ["tachikawa-kin-kaitori","hachioji-kin-kaitori","tokyo-kin-kaitori"]),
 ("tama-kin-kaitori","多摩","東京都","kanto","多摩ニュータウンの計画都市",
  ["多摩センター","永山","聖蹟桜ヶ丘方面"],
  "多摩市は多摩ニュータウンを中心に発展した計画都市です。ファミリー層が多く、生前整理や不用品とあわせた金製品の出張買取が利用されています。",
  ["machida-kin-kaitori","hachioji-kin-kaitori","kin-souzoku-baikyaku"]),
 ("koganei-kin-kaitori","小金井","東京都","kanto","小金井公園と中央線の住宅地",
  ["武蔵小金井駅周辺","東小金井","本町"],
  "小金井市は小金井公園を擁する中央線沿線の住宅地です。武蔵小金井駅周辺の再開発で商業施設が増え、買取店も利用しやすくなっています。",
  ["kichijoji-kin-kaitori","tachikawa-kin-kaitori","tokyo-kin-kaitori"]),
 ("kokubunji-kin-kaitori","国分寺","東京都","kanto","中央線の交通結節点",
  ["国分寺駅周辺","西国分寺","本多"],
  "国分寺市は中央線と西武線が交わる多摩の交通結節点です。駅ビルや商店街に買取店が点在し、通勤帰りにも金製品を売却しやすい立地です。",
  ["tachikawa-kin-kaitori","kichijoji-kin-kaitori","tokyo-kin-kaitori"]),
 ("ome-kin-kaitori","青梅","東京都","kanto","多摩西部の自然豊かな都市",
  ["青梅駅周辺","河辺","東青梅"],
  "青梅市は多摩西部に位置する自然豊かな都市です。郊外型の店舗や出張買取が中心で、自宅にいながら金製品を査定に出せる方法が便利です。",
  ["hachioji-kin-kaitori","tachikawa-kin-kaitori","kin-takaku-uru"]),
 # ===== 埼玉 =====
 ("kumagaya-kin-kaitori","熊谷","埼玉県","kanto","県北の中核・暑さで有名な都市",
  ["熊谷駅周辺","籠原","妻沼方面"],
  "熊谷市は埼玉県北部の中核都市で、新幹線も停車する交通の要衝です。駅周辺に買取店が集まり、県北一帯から金製品の売却需要が集まります。",
  ["omiya-kin-kaitori","takasaki-kin-kaitori","kin-kaitori-souba"]),
 ("ageo-kin-kaitori","上尾","埼玉県","kanto","県央のベッドタウン",
  ["上尾駅周辺","北上尾","原市"],
  "上尾市はさいたま市に隣接する県央のベッドタウンです。高崎線沿線に住宅地が広がり、駅前の買取店や出張買取が利用しやすい環境です。",
  ["omiya-kin-kaitori","saitama-ken-kin-kaitori","kin-takaku-uru"]),
 ("fukaya-kin-kaitori","深谷","埼玉県","kanto","渋沢栄一ゆかりの県北都市",
  ["深谷駅周辺","岡部","花園方面"],
  "深谷市は渋沢栄一の生誕地として知られる県北の都市です。郊外店舗や出張買取が中心で、近隣の熊谷・本庄からの来店もあります。",
  ["kumagaya-kin-kaitori","takasaki-kin-kaitori","saitama-ken-kin-kaitori"]),
 ("niiza-kin-kaitori","新座","埼玉県","kanto","東京に接する県南の住宅都市",
  ["志木駅周辺","新座駅周辺","大泉学園方面"],
  "新座市は練馬区に隣接する県南の住宅都市です。東京方面へのアクセスが良く、買い物や通勤の動線上で金製品を売却しやすい地域です。",
  ["tokorozawa-kin-kaitori","nerima-kin-kaitori","tokyo-kin-kaitori"]),
 ("asaka-kin-kaitori","朝霞","埼玉県","kanto","東京近接の県南都市",
  ["朝霞駅周辺","朝霞台","北朝霞"],
  "朝霞市は東武東上線・武蔵野線が通る県南の住宅都市です。都心へのアクセスが良く、駅周辺の買取店や出張買取が利用されています。",
  ["tokorozawa-kin-kaitori","omiya-kin-kaitori","kin-takaku-uru"]),
 ("sayama-kin-kaitori","狭山","埼玉県","kanto","狭山茶で知られる県西の都市",
  ["狭山市駅周辺","入曽","新狭山"],
  "狭山市は狭山茶で知られる県西部の都市です。西武新宿線沿線に住宅地が広がり、郊外店舗や出張買取で金製品を売却できます。",
  ["tokorozawa-kin-kaitori","kawagoe-kin-kaitori","kin-kaitori-souba"]),
 ("kuki-kin-kaitori","久喜","埼玉県","kanto","県東の交通結節点",
  ["久喜駅周辺","鷲宮","栗橋方面"],
  "久喜市はJR・東武が交わる県東部の交通結節点です。郊外型の買取店が点在し、県東一帯から金製品の売却需要が集まります。",
  ["kasukabe-kin-kaitori","omiya-kin-kaitori","kin-takaku-uru"]),
 # ===== 千葉 =====
 ("narita-kin-kaitori","成田","千葉県","kanto","国際空港と成田山の門前町",
  ["成田駅周辺","成田空港","公津の杜"],
  "成田市は国際空港と成田山新勝寺の門前町を抱える都市です。観光客や住民向けに買取店が点在し、出張買取の対応エリアも広い地域です。",
  ["chiba-kin-kaitori","funabashi-kin-kaitori","kin-kaitori-souba"]),
 ("urayasu-kin-kaitori","浦安","千葉県","kanto","テーマパークの街・東京湾岸",
  ["新浦安","舞浜","浦安駅周辺"],
  "浦安市は東京ディズニーリゾートを擁する東京湾岸の都市です。都心並みの利便性で、新浦安・舞浜周辺で金製品を売却しやすい環境です。",
  ["ichikawa-chiba-kin-kaitori","funabashi-kin-kaitori","kin-necklace-kaitori"]),
 ("ichihara-kin-kaitori","市原","千葉県","kanto","京葉工業地帯の中核",
  ["五井","八幡宿","姉ヶ崎"],
  "市原市は京葉工業地帯を抱える千葉県中部の都市です。広い市域に郊外店舗が点在し、出張買取で金製品を売却するスタイルが便利です。",
  ["chiba-kin-kaitori","kisarazu-kin-kaitori","kin-takaku-uru"]),
 ("nagareyama-kin-kaitori","流山","千葉県","kanto","つくばエクスプレスで人口増の都市",
  ["流山おおたかの森","南流山","流山駅周辺"],
  "流山市はつくばエクスプレス沿線の再開発で人口が急増している都市です。新しい商業施設が増え、おおたかの森周辺で金製品を売却しやすくなっています。",
  ["matsudo-kin-kaitori","kashiwa-kin-kaitori","kin-kaitori-souba"]),
 ("kisarazu-kin-kaitori","木更津","千葉県","kanto","アクアラインの玄関口",
  ["木更津駅周辺","金田","請西"],
  "木更津市は東京湾アクアラインの玄関口にあたる房総の都市です。アウトレット周辺の開発が進み、出張買取とあわせて金製品を売却できます。",
  ["chiba-kin-kaitori","ichihara-kin-kaitori","kin-takaku-uru"]),
 ("sakura-chiba-kin-kaitori","佐倉","千葉県","kanto","城下町と歴史の街",
  ["佐倉駅周辺","京成佐倉","ユーカリが丘方面"],
  "佐倉市は江戸時代の城下町で、歴史民俗博物館でも知られる千葉県北部の都市です。京成・JR沿線の住宅地で、出張買取の需要が高い地域です。",
  ["chiba-kin-kaitori","narita-kin-kaitori","kin-souzoku-baikyaku"]),
 ("noda-chiba-kin-kaitori","野田","千葉県","kanto","醤油醸造で知られる県北西の都市",
  ["野田市駅周辺","愛宕","川間"],
  "野田市は醤油醸造で全国的に知られる県北西部の都市です。東武アーバンパークライン沿線に住宅地が広がり、出張買取が利用しやすい地域です。",
  ["kashiwa-kin-kaitori","matsudo-kin-kaitori","kin-kaitori-souba"]),
 ("abiko-kin-kaitori","我孫子","千葉県","kanto","手賀沼に面した住宅都市",
  ["我孫子駅周辺","天王台","新木方面"],
  "我孫子市は手賀沼に面した常磐線沿線の住宅都市です。都心への通勤圏で、駅周辺や出張買取で金製品を手軽に売却できます。",
  ["kashiwa-kin-kaitori","matsudo-kin-kaitori","kin-takaku-uru"]),
 # ===== 神奈川 =====
 ("chigasaki-kin-kaitori","茅ヶ崎","神奈川県","kanto","湘南を代表するサーフタウン",
  ["茅ヶ崎駅周辺","香川","辻堂方面"],
  "茅ヶ崎市は湘南を代表する海沿いの都市です。藤沢・平塚に近く、駅周辺の買取店や出張買取で金製品を売却しやすい環境です。",
  ["fujisawa-kin-kaitori","hiratsuka-kin-kaitori","kin-necklace-kaitori"]),
 ("kamakura-kin-kaitori","鎌倉","神奈川県","kanto","古都として知られる観光都市",
  ["鎌倉駅周辺","大船","北鎌倉"],
  "鎌倉市は寺社と海に囲まれた歴史ある観光都市です。大船駅周辺に商業施設が集まり、古い装飾品や金製品の売却相談も多い地域です。",
  ["fujisawa-kin-kaitori","yokohama-kin-kaitori","kin-souzoku-baikyaku"]),
 ("ebina-kin-kaitori","海老名","神奈川県","kanto","県央の交通結節点",
  ["海老名駅周辺","さがみ野","厚木方面"],
  "海老名市は小田急・相鉄・JRが交わる県央の交通結節点です。大型商業施設が集まる海老名駅周辺で、金製品を売却しやすい環境が整っています。",
  ["atsugi-kin-kaitori","sagamihara-kin-kaitori","kin-kaitori-souba"]),
 ("zama-kin-kaitori","座間","神奈川県","kanto","ひまわりで知られる県央の都市",
  ["相武台前","座間駅周辺","さがみ野"],
  "座間市はひまわり畑で知られる県央の都市です。相模原・海老名に隣接し、郊外店舗や出張買取で金製品を売却できます。",
  ["sagamihara-kin-kaitori","atsugi-kin-kaitori","kin-takaku-uru"]),
 ("hadano-kin-kaitori","秦野","神奈川県","kanto","丹沢の麓に広がる都市",
  ["秦野駅周辺","渋沢","鶴巻温泉方面"],
  "秦野市は丹沢山地の麓に広がる県西部の都市です。小田急沿線に住宅地が点在し、出張買取で金製品を自宅から売却できます。",
  ["hiratsuka-kin-kaitori","atsugi-kin-kaitori","kin-kaitori-souba"]),
 ("isehara-kin-kaitori","伊勢原","神奈川県","kanto","大山詣でで知られる県西の都市",
  ["伊勢原駅周辺","愛甲石田","大山方面"],
  "伊勢原市は大山詣でで知られる県西部の都市です。小田急沿線の住宅地で、駅前店舗や出張買取をつかった金製品の売却が一般的です。",
  ["atsugi-kin-kaitori","hiratsuka-kin-kaitori","kin-takaku-uru"]),
 # ===== 茨城 =====
 ("hitachi-kin-kaitori","日立","茨城県","kanto","企業城下町として発展した港湾都市",
  ["日立駅周辺","多賀","常陸多賀"],
  "日立市は大手メーカーの企業城下町として発展した県北の港湾都市です。常磐線沿線に商業施設が集まり、金製品の売却相談が寄せられます。",
  ["mito-kin-kaitori","tsukuba-kin-kaitori","kin-kaitori-souba"]),
 ("tsuchiura-kin-kaitori","土浦","茨城県","kanto","霞ヶ浦と花火大会の街",
  ["土浦駅周辺","荒川沖","神立"],
  "土浦市は霞ヶ浦に面し、全国的な花火大会で知られる県南の都市です。つくば・水戸へのアクセスも良く、出張買取の需要が高い地域です。",
  ["tsukuba-kin-kaitori","mito-kin-kaitori","kin-takaku-uru"]),
 ("hitachinaka-kin-kaitori","ひたちなか","茨城県","kanto","海浜公園で知られる県央の都市",
  ["勝田駅周辺","那珂湊","佐和"],
  "ひたちなか市は国営ひたち海浜公園で知られる県央の都市です。勝田駅周辺に商業施設が集まり、近隣の水戸・日立とあわせて売却先を比較できます。",
  ["mito-kin-kaitori","hitachi-kin-kaitori","kin-kaitori-souba"]),
 ("koga-ibaraki-kin-kaitori","古河","茨城県","kanto","県西の歴史ある都市",
  ["古河駅周辺","総和","新古河方面"],
  "古河市は栃木・埼玉に接する県西の歴史ある都市です。郊外店舗や出張買取が中心で、近隣の小山方面からの来店もあります。",
  ["mito-kin-kaitori","oyama-kin-kaitori","kin-takaku-uru"]),
 # ===== 栃木 =====
 ("oyama-kin-kaitori","小山","栃木県","kanto","新幹線も停まる県南の交通要衝",
  ["小山駅周辺","間々田","小山市役所周辺"],
  "小山市は新幹線も停車する県南の交通要衝です。駅周辺に商業施設と買取店が集まり、栃木県南一帯から金製品の売却需要が集まります。",
  ["utsunomiya-kin-kaitori","koga-ibaraki-kin-kaitori","kin-kaitori-souba"]),
 ("ashikaga-kin-kaitori","足利","栃木県","kanto","足利学校と織物の歴史都市",
  ["足利市駅周辺","足利駅周辺","福居"],
  "足利市は日本最古の学校・足利学校と織物の歴史で知られる両毛の都市です。郊外店舗や出張買取で、古い装飾品や金製品を売却できます。",
  ["utsunomiya-kin-kaitori","kiryu-kin-kaitori","kin-souzoku-baikyaku"]),
 ("sano-kin-kaitori","佐野","栃木県","kanto","アウトレットと佐野ラーメンの街",
  ["佐野駅周辺","田沼方面","佐野市役所周辺"],
  "佐野市はアウトレットモールと佐野ラーメンで知られる県南西の都市です。買い物ついでに金製品を査定に出しやすく、出張買取も利用できます。",
  ["ashikaga-kin-kaitori","oyama-kin-kaitori","kin-takaku-uru"]),
 # ===== 群馬 =====
 ("isesaki-kin-kaitori","伊勢崎","群馬県","kanto","両毛地域の工業都市",
  ["伊勢崎駅周辺","境","伊勢崎市役所周辺"],
  "伊勢崎市は両毛地域に位置する群馬県南部の工業都市です。郊外型の買取店が点在し、前橋・高崎とあわせて売却先を比較しやすい地域です。",
  ["maebashi-kin-kaitori","takasaki-kin-kaitori","kin-kaitori-souba"]),
 ("ota-gunma-kin-kaitori","太田","群馬県","kanto","自動車メーカーの企業城下町",
  ["太田駅周辺","韮川","木崎方面"],
  "太田市は自動車メーカーの企業城下町として発展した県東部の都市です。郊外店舗や出張買取が中心で、東毛一帯から売却需要が集まります。",
  ["maebashi-kin-kaitori","isesaki-kin-kaitori","kin-takaku-uru"]),
 ("kiryu-kin-kaitori","桐生","群馬県","kanto","織物の歴史で知られる都市",
  ["桐生駅周辺","新桐生","相生方面"],
  "桐生市は「西の西陣、東の桐生」と称された織物の街です。歴史ある市街地に郊外店舗が点在し、古い金製品の売却相談も寄せられます。",
  ["maebashi-kin-kaitori","ashikaga-kin-kaitori","kin-souzoku-baikyaku"]),
 # ===== 新潟・北陸 =====
 ("nagaoka-kin-kaitori","長岡","新潟県","chubu","花火大会で知られる中越の中核",
  ["長岡駅周辺","宮内","長岡市役所周辺"],
  "長岡市は大花火大会で知られる新潟県中越の中核都市です。長岡駅周辺に商業施設が集まり、中越一帯から金製品の売却需要が集まります。",
  ["niigata-kin-kaitori","joetsu-kin-kaitori","kin-kaitori-souba"]),
 ("joetsu-kin-kaitori","上越","新潟県","chubu","高田・直江津からなる上越の都市",
  ["高田駅周辺","直江津","春日山方面"],
  "上越市は高田と直江津を中心とする新潟県南西部の都市です。郊外店舗や出張買取が中心で、上越一帯の金製品売却に対応しています。",
  ["niigata-kin-kaitori","nagaoka-kin-kaitori","kin-takaku-uru"]),
 # ===== 長野・山梨 =====
 ("matsumoto-kin-kaitori","松本","長野県","chubu","国宝・松本城を擁する観光都市",
  ["松本駅周辺","松本城周辺","浅間温泉方面"],
  "松本市は国宝・松本城を擁する中信地方の中核都市です。駅周辺と城下の商業エリアに買取店が点在し、観光客・住民の売却に対応します。",
  ["nagano-kin-kaitori","ueda-kin-kaitori","kin-kaitori-souba"]),
 ("ueda-kin-kaitori","上田","長野県","chubu","真田氏ゆかりの城下町",
  ["上田駅周辺","上田城周辺","別所温泉方面"],
  "上田市は真田氏ゆかりの城下町として知られる東信の都市です。新幹線も停車し、駅周辺の店舗や出張買取で金製品を売却できます。",
  ["nagano-kin-kaitori","matsumoto-kin-kaitori","kin-souzoku-baikyaku"]),
 # ===== 静岡 =====
 ("numazu-kin-kaitori","沼津","静岡県","chubu","駿河湾に面した東部の港町",
  ["沼津駅周辺","大手町","沼津港方面"],
  "沼津市は駿河湾に面した静岡県東部の港町です。沼津駅周辺に商業施設が集まり、東部一帯から金製品の売却需要が集まります。",
  ["shizuoka-kin-kaitori","fuji-shizuoka-kin-kaitori","kin-kaitori-souba"]),
 ("fuji-shizuoka-kin-kaitori","富士","静岡県","chubu","富士山を望む製紙の街",
  ["富士駅周辺","吉原","新富士方面"],
  "富士市は富士山を望む製紙業の盛んな県東部の都市です。郊外店舗や出張買取が利用しやすく、近隣の沼津・富士宮とあわせて比較できます。",
  ["shizuoka-kin-kaitori","numazu-kin-kaitori","kin-takaku-uru"]),
 ("fujieda-kin-kaitori","藤枝","静岡県","chubu","志太地域の住宅都市",
  ["藤枝駅周辺","焼津方面","藤枝市役所周辺"],
  "藤枝市は志太地域に位置する県中部の住宅都市です。静岡市にも近く、駅前店舗や出張買取で金製品を手軽に売却できます。",
  ["shizuoka-kin-kaitori","hamamatsu-kin-kaitori","kin-kaitori-souba"]),
 ("iwata-kin-kaitori","磐田","静岡県","chubu","サッカーと製造業の西部都市",
  ["磐田駅周辺","豊田町","磐田市役所周辺"],
  "磐田市はサッカーと製造業で知られる県西部の都市です。浜松に隣接し、郊外店舗や出張買取で金製品を売却しやすい環境です。",
  ["hamamatsu-kin-kaitori","shizuoka-kin-kaitori","kin-takaku-uru"]),
 # ===== 愛知 =====
 ("kasugai-kin-kaitori","春日井","愛知県","chubu","名古屋近郊のベッドタウン",
  ["春日井駅周辺","高蔵寺","勝川"],
  "春日井市は名古屋に隣接するベッドタウンです。中央線沿線に住宅地が広がり、駅前店舗や出張買取で金製品を売却しやすい地域です。",
  ["nagoya-kin-kaitori","komaki-kin-kaitori","kin-kaitori-souba"]),
 ("anjo-kin-kaitori","安城","愛知県","chubu","三河の製造業都市",
  ["安城駅周辺","三河安城","安城市役所周辺"],
  "安城市は自動車部品メーカーが集まる西三河の製造業都市です。新幹線三河安城駅もあり、駅周辺や出張買取で金製品を売却できます。",
  ["okazaki-kin-kaitori","kariya-kin-kaitori","kin-takaku-uru"]),
 ("kariya-kin-kaitori","刈谷","愛知県","chubu","自動車部品メーカーの集積地",
  ["刈谷駅周辺","逢妻","刈谷市役所周辺"],
  "刈谷市は大手自動車部品メーカーが本社を構える西三河の都市です。駅周辺に商業施設が集まり、金製品の売却にも便利な立地です。",
  ["anjo-kin-kaitori","toyota-kin-kaitori","kin-kaitori-souba"]),
 ("toyokawa-kin-kaitori","豊川","愛知県","chubu","豊川稲荷の門前都市",
  ["豊川駅周辺","国府","諏訪町"],
  "豊川市は豊川稲荷の門前町として知られる東三河の都市です。豊橋に近く、郊外店舗や出張買取で金製品を売却しやすい地域です。",
  ["toyohashi-kin-kaitori","okazaki-kin-kaitori","kin-takaku-uru"]),
 ("nishio-kin-kaitori","西尾","愛知県","chubu","抹茶で知られる西三河の都市",
  ["西尾駅周辺","吉良方面","西尾市役所周辺"],
  "西尾市は抹茶の産地として知られる西三河の都市です。郊外店舗や出張買取が中心で、近隣の岡崎・安城とあわせて売却先を比較できます。",
  ["okazaki-kin-kaitori","anjo-kin-kaitori","kin-kaitori-souba"]),
 ("komaki-kin-kaitori","小牧","愛知県","chubu","県営名古屋空港のある尾張の都市",
  ["小牧駅周辺","味岡","小牧市役所周辺"],
  "小牧市は県営名古屋空港を擁する尾張北部の都市です。郊外型の買取店が点在し、名古屋方面とあわせて金製品の売却先を比較できます。",
  ["kasugai-kin-kaitori","nagoya-kin-kaitori","kin-takaku-uru"]),
 ("handa-kin-kaitori","半田","愛知県","chubu","酢と山車祭りで知られる知多の都市",
  ["半田駅周辺","亀崎","成岩"],
  "半田市は酢醸造と山車祭りで知られる知多半島の中核都市です。郊外店舗や出張買取で、知多一帯の金製品売却に対応しています。",
  ["nagoya-kin-kaitori","kariya-kin-kaitori","kin-kaitori-souba"]),
 # ===== 岐阜・三重 =====
 ("ogaki-kin-kaitori","大垣","岐阜県","chubu","「水の都」と呼ばれる西濃の中核",
  ["大垣駅周辺","大垣市役所周辺","荒尾方面"],
  "大垣市は「水の都」と呼ばれる西濃地域の中核都市です。岐阜・名古屋へのアクセスが良く、駅周辺や出張買取で金製品を売却できます。",
  ["gifu-kin-kaitori","nagoya-kin-kaitori","kin-kaitori-souba"]),
 ("suzuka-kin-kaitori","鈴鹿","三重県","chubu","サーキットで知られる北勢の都市",
  ["近鉄白子駅周辺","平田町","鈴鹿市役所周辺"],
  "鈴鹿市はモータースポーツのサーキットで知られる北勢地域の都市です。近鉄沿線に住宅地が広がり、出張買取で金製品を売却できます。",
  ["tsu-kin-kaitori","yokkaichi-kin-kaitori","kin-takaku-uru"]),
 ("matsusaka-kin-kaitori","松阪","三重県","chubu","松阪牛で知られる中勢の都市",
  ["松阪駅周辺","松阪市役所周辺","大津町"],
  "松阪市は松阪牛で全国的に知られる中勢地域の都市です。津・伊勢に近く、郊外店舗や出張買取で金製品を売却しやすい地域です。",
  ["tsu-kin-kaitori","suzuka-kin-kaitori","kin-kaitori-souba"]),
 # ===== 滋賀・京都 =====
 ("kusatsu-shiga-kin-kaitori","草津","滋賀県","kinki","東海道と中山道が交わる宿場町",
  ["草津駅周辺","南草津","草津市役所周辺"],
  "草津市は東海道と中山道が交わる宿場町を起源とする湖南の都市です。JR沿線で京阪神への通勤圏にあり、駅前で金製品を売却しやすい環境です。",
  ["otsu-kin-kaitori","kyoto-kin-kaitori","kin-kaitori-souba"]),
 ("uji-kin-kaitori","宇治","京都府","kinki","平等院と宇治茶で知られる古都",
  ["宇治駅周辺","大久保","黄檗方面"],
  "宇治市は平等院と宇治茶で知られる京都府南部の古都です。京都市に近く、駅周辺や出張買取で金製品や古い装飾品を売却できます。",
  ["kyoto-kin-kaitori","otsu-kin-kaitori","kin-souzoku-baikyaku"]),
 # ===== 大阪 =====
 ("takatsuki-kin-kaitori","高槻","大阪府","kinki","北摂の中核・大阪と京都の中間",
  ["高槻駅周辺","富田","高槻市役所周辺"],
  "高槻市は大阪と京都の中間に位置する北摂の中核都市です。JR・阪急沿線に商業施設が集まり、駅前で金製品を売却しやすい環境です。",
  ["osaka-kin-kaitori","suita-kin-kaitori","kin-kaitori-souba"]),
 ("ibaraki-osaka-kin-kaitori","茨木","大阪府","kinki","北摂のベッドタウン",
  ["茨木駅周辺","南茨木","茨木市役所周辺"],
  "茨木市は大阪・京都の通勤圏にある北摂のベッドタウンです。JR・阪急・モノレール沿線に住宅地が広がり、出張買取の需要が高い地域です。",
  ["osaka-kin-kaitori","takatsuki-kin-kaitori","kin-takaku-uru"]),
 ("yao-kin-kaitori","八尾","大阪府","kinki","中河内のものづくり都市",
  ["近鉄八尾駅周辺","久宝寺","八尾市役所周辺"],
  "八尾市は中小製造業が集まる中河内の都市です。近鉄・JR沿線に商業地が広がり、駅周辺の買取店や出張買取で金製品を売却できます。",
  ["osaka-kin-kaitori","higashiosaka-kin-kaitori","kin-kaitori-souba"]),
 ("kishiwada-kin-kaitori","岸和田","大阪府","kinki","だんじり祭りで知られる泉州の都市",
  ["岸和田駅周辺","春木","岸和田市役所周辺"],
  "岸和田市はだんじり祭りで全国的に知られる泉州の都市です。南海沿線に商業施設が集まり、泉州一帯から金製品の売却需要が集まります。",
  ["sakai-kin-kaitori","osaka-kin-kaitori","kin-takaku-uru"]),
 ("neyagawa-kin-kaitori","寝屋川","大阪府","kinki","北河内のベッドタウン",
  ["寝屋川市駅周辺","香里園","寝屋川市役所周辺"],
  "寝屋川市は京阪沿線に広がる北河内のベッドタウンです。大阪市内へのアクセスが良く、駅周辺や出張買取で金製品を売却できます。",
  ["osaka-kin-kaitori","hirakata-kin-kaitori","kin-kaitori-souba"]),
 ("izumi-osaka-kin-kaitori","和泉","大阪府","kinki","泉北の住宅都市",
  ["和泉中央","泉大津方面","和泉市役所周辺"],
  "和泉市は泉北ニュータウンを抱える泉州北部の住宅都市です。郊外型の商業施設が多く、出張買取とあわせて金製品を売却できます。",
  ["sakai-kin-kaitori","kishiwada-kin-kaitori","kin-takaku-uru"]),
 ("moriguchi-kin-kaitori","守口","大阪府","kinki","大手電機メーカー発祥の都市",
  ["守口市駅周辺","京阪守口","守口市役所周辺"],
  "守口市は大手電機メーカー発祥の地として知られる北河内の都市です。大阪市に隣接し、駅前店舗や出張買取で金製品を売却しやすい立地です。",
  ["osaka-kin-kaitori","neyagawa-kin-kaitori","kin-kaitori-souba"]),
 ("ikeda-osaka-kin-kaitori","池田","大阪府","kinki","北摂の落ち着いた住宅都市",
  ["池田駅周辺","石橋方面","池田市役所周辺"],
  "池田市はインスタントラーメン発祥の地として知られる北摂の住宅都市です。阪急沿線で大阪・神戸へのアクセスが良く、金製品を売却しやすい環境です。",
  ["toyonaka-kin-kaitori","osaka-kin-kaitori","kin-takaku-uru"]),
 # ===== 兵庫 =====
 ("akashi-kin-kaitori","明石","兵庫県","kinki","子午線と明石海峡の街",
  ["明石駅周辺","大久保","西明石"],
  "明石市は日本標準時子午線と明石海峡で知られる東播磨の都市です。神戸に隣接し、駅前店舗や出張買取で金製品を売却しやすい環境です。",
  ["kobe-kin-kaitori","himeji-kin-kaitori","kin-kaitori-souba"]),
 ("kakogawa-kin-kaitori","加古川","兵庫県","kinki","東播磨の中核都市",
  ["加古川駅周辺","東加古川","加古川市役所周辺"],
  "加古川市は東播磨地域の中核都市です。神戸・姫路の中間に位置し、郊外店舗や出張買取で金製品を売却しやすい地域です。",
  ["himeji-kin-kaitori","akashi-kin-kaitori","kin-takaku-uru"]),
 ("takarazuka-kin-kaitori","宝塚","兵庫県","kinki","歌劇と温泉で知られる阪神北の都市",
  ["宝塚駅周辺","逆瀬川","売布神社方面"],
  "宝塚市は歌劇と温泉で知られる阪神北の住宅都市です。阪急・JR沿線の落ち着いた街並みで、出張買取の需要が高い地域です。",
  ["nishinomiya-kin-kaitori","itami-kin-kaitori","kin-souzoku-baikyaku"]),
 ("itami-kin-kaitori","伊丹","兵庫県","kinki","空港と酒造の街",
  ["伊丹駅周辺","塚口方面","伊丹市役所周辺"],
  "伊丹市は大阪国際空港と清酒発祥の地として知られる阪神間の都市です。大阪・神戸へのアクセスが良く、駅前で金製品を売却しやすい立地です。",
  ["amagasaki-kin-kaitori","takarazuka-kin-kaitori","kin-kaitori-souba"]),
 ("kawanishi-kin-kaitori","川西","兵庫県","kinki","阪神北の住宅都市",
  ["川西能勢口駅周辺","多田","川西池田"],
  "川西市は阪急・能勢電が通る阪神北の住宅都市です。大阪へのアクセスが良く、駅周辺や出張買取で金製品を手軽に売却できます。",
  ["itami-kin-kaitori","takarazuka-kin-kaitori","kin-takaku-uru"]),
 ("sanda-kin-kaitori","三田","兵庫県","kinki","ニュータウンで人口が増えた都市",
  ["三田駅周辺","ウッディタウン","三田市役所周辺"],
  "三田市はニュータウン開発で人口が増えた兵庫県南東部の都市です。神戸・大阪の通勤圏にあり、出張買取で金製品を自宅から売却できます。",
  ["kobe-kin-kaitori","takarazuka-kin-kaitori","kin-kaitori-souba"]),
 # ===== 中国・四国 =====
 ("fukuyama-kin-kaitori","福山","広島県","chugoku-shikoku","備後地方の中核都市",
  ["福山駅周辺","松永","福山市役所周辺"],
  "福山市は新幹線も停車する備後地方の中核都市です。福山城に近い駅周辺に商業施設が集まり、備後一帯から金製品の売却需要が集まります。",
  ["hiroshima-kin-kaitori","kurashiki-kin-kaitori","kin-kaitori-souba"]),
 ("kure-kin-kaitori","呉","広島県","chugoku-shikoku","海軍と造船の歴史を持つ港町",
  ["呉駅周辺","広","呉市役所周辺"],
  "呉市は造船と海軍の歴史で知られる広島県南部の港町です。広島市にも近く、駅周辺や出張買取で金製品を売却しやすい地域です。",
  ["hiroshima-kin-kaitori","fukuyama-kin-kaitori","kin-takaku-uru"]),
 ("shimonoseki-kin-kaitori","下関","山口県","chugoku-shikoku","本州西端・ふぐと関門の街",
  ["下関駅周辺","新下関","唐戸方面"],
  "下関市はふぐと関門海峡で知られる本州最西端の都市です。北九州とも近く、駅周辺や出張買取で金製品を売却しやすい地域です。",
  ["yamaguchi-kin-kaitori","kitakyushu-kin-kaitori","kin-kaitori-souba"]),
 ("tottori-kin-kaitori","鳥取","鳥取県","chugoku-shikoku","砂丘で知られる県庁所在地",
  ["鳥取駅周辺","鳥取市役所周辺","湖山方面"],
  "鳥取市は鳥取砂丘で知られる鳥取県の県庁所在地です。駅周辺に商業施設が集まり、県東部一帯から金製品の売却需要が集まります。",
  ["matsue-kin-kaitori","okayama-kin-kaitori","kin-takaku-uru"]),
 ("tsuyama-kin-kaitori","津山","岡山県","chugoku-shikoku","美作地方の中核都市",
  ["津山駅周辺","津山市役所周辺","院庄方面"],
  "津山市は岡山県北部・美作地方の中核都市です。津山城下の市街地に商業施設が点在し、出張買取で金製品を売却しやすい地域です。",
  ["okayama-kin-kaitori","tottori-kin-kaitori","kin-kaitori-souba"]),
 ("imabari-kin-kaitori","今治","愛媛県","chugoku-shikoku","タオルとしまなみ海道の街",
  ["今治駅周辺","今治市役所周辺","波止浜方面"],
  "今治市はタオル産業としまなみ海道の起点で知られる愛媛県東予の都市です。郊外店舗や出張買取で、東予一帯の金製品売却に対応します。",
  ["matsuyama-kin-kaitori","takamatsu-kin-kaitori","kin-takaku-uru"]),
 # ===== 九州 =====
 ("omuta-kin-kaitori","大牟田","福岡県","kyushu","三池炭鉱で栄えた県南の都市",
  ["大牟田駅周辺","新栄町","大牟田市役所周辺"],
  "大牟田市は三池炭鉱で栄えた福岡県南部の都市です。熊本県にも近く、駅周辺や出張買取で金製品を売却しやすい地域です。",
  ["kurume-kin-kaitori","fukuoka-kin-kaitori","kin-kaitori-souba"]),
 ("iizuka-kin-kaitori","飯塚","福岡県","kyushu","筑豊地域の中核都市",
  ["飯塚駅周辺","新飯塚","飯塚市役所周辺"],
  "飯塚市はかつて炭鉱で栄えた筑豊地域の中核都市です。福岡・北九州の中間に位置し、出張買取で金製品を売却しやすい地域です。",
  ["fukuoka-kin-kaitori","kitakyushu-kin-kaitori","kin-takaku-uru"]),
 ("kasuga-fukuoka-kin-kaitori","春日","福岡県","kyushu","福岡市に隣接するベッドタウン",
  ["春日駅周辺","春日市役所周辺","大野城方面"],
  "春日市は福岡市に隣接する人口密度の高いベッドタウンです。福岡都市圏の利便性で、駅前店舗や出張買取で金製品を売却しやすい環境です。",
  ["fukuoka-kin-kaitori","kurume-kin-kaitori","kin-kaitori-souba"]),
 ("sasebo-kin-kaitori","佐世保","長崎県","kyushu","軍港とハウステンボスの街",
  ["佐世保駅周辺","佐世保市役所周辺","大塔方面"],
  "佐世保市は軍港とハウステンボスで知られる長崎県北部の都市です。市街地に商業施設が集まり、県北一帯から金製品の売却需要が集まります。",
  ["nagasaki-kin-kaitori","fukuoka-kin-kaitori","kin-takaku-uru"]),
 ("yatsushiro-kin-kaitori","八代","熊本県","kyushu","県南の中核・い草の産地",
  ["八代駅周辺","新八代","八代市役所周辺"],
  "八代市はい草の産地として知られる熊本県南部の中核都市です。新幹線新八代駅もあり、駅周辺や出張買取で金製品を売却できます。",
  ["kumamoto-kin-kaitori","kagoshima-kin-kaitori","kin-kaitori-souba"]),
 ("kirishima-kin-kaitori","霧島","鹿児島県","kyushu","温泉と空港のある県央の都市",
  ["国分駅周辺","隼人","霧島市役所周辺"],
  "霧島市は霧島温泉と鹿児島空港を擁する県央の都市です。郊外店舗や出張買取が中心で、鹿児島市方面とあわせて売却先を比較できます。",
  ["kagoshima-kin-kaitori","miyazaki-kin-kaitori","kin-takaku-uru"]),
 ("okinawa-shi-kin-kaitori","沖縄市","沖縄県","kyushu","コザの愛称で知られる本島中部の都市",
  ["胡屋","コザ","沖縄市役所周辺"],
  "沖縄市はコザの愛称で知られる沖縄本島中部の中核都市です。那覇に次ぐ人口を抱え、市街地の店舗や出張買取で金製品を売却できます。",
  ["naha-kin-kaitori","kagoshima-kin-kaitori","kin-kaitori-souba"]),
 # ===== 北海道・東北 =====
 ("obihiro-kin-kaitori","帯広","北海道","hokkaido-tohoku","十勝平野の中心都市",
  ["帯広駅周辺","西帯広","帯広市役所周辺"],
  "帯広市は農業が盛んな十勝平野の中心都市です。駅周辺に商業施設が集まり、十勝一帯から金製品の売却需要が集まります。",
  ["sapporo-kin-kaitori","asahikawa-kin-kaitori","kin-takaku-uru"]),
 ("kushiro-kin-kaitori","釧路","北海道","hokkaido-tohoku","道東を代表する港湾都市",
  ["釧路駅周辺","春採方面","釧路市役所周辺"],
  "釧路市は湿原と漁港で知られる道東を代表する港湾都市です。市街地に郊外店舗が点在し、出張買取で金製品を売却しやすい地域です。",
  ["sapporo-kin-kaitori","obihiro-kin-kaitori","kin-kaitori-souba"]),
 ("tomakomai-kin-kaitori","苫小牧","北海道","hokkaido-tohoku","港湾と工業の道央都市",
  ["苫小牧駅周辺","沼ノ端","苫小牧市役所周辺"],
  "苫小牧市は港湾と製紙・工業で発展した道央の都市です。札幌・新千歳空港にも近く、郊外店舗や出張買取で金製品を売却できます。",
  ["sapporo-kin-kaitori","hakodate-kin-kaitori","kin-takaku-uru"]),
 ("hachinohe-kin-kaitori","八戸","青森県","hokkaido-tohoku","県南の港湾・工業都市",
  ["八戸駅周辺","本八戸","八戸市役所周辺"],
  "八戸市は漁港と工業で知られる青森県南部の都市です。新幹線も停車し、駅周辺や出張買取で金製品を売却しやすい地域です。",
  ["aomori-kin-kaitori","morioka-kin-kaitori","kin-kaitori-souba"]),
 ("hirosaki-kin-kaitori","弘前","青森県","hokkaido-tohoku","城と桜で知られる津軽の中心都市",
  ["弘前駅周辺","中央弘前","弘前城周辺"],
  "弘前市は弘前城と桜まつりで知られる津軽地方の中心都市です。城下の市街地に商業施設が集まり、出張買取で金製品を売却できます。",
  ["aomori-kin-kaitori","hachinohe-kin-kaitori","kin-souzoku-baikyaku"]),
 ("ichinoseki-kin-kaitori","一関","岩手県","hokkaido-tohoku","岩手県南の交通要衝",
  ["一ノ関駅周辺","山目方面","一関市役所周辺"],
  "一関市は新幹線も停車する岩手県南の交通要衝です。宮城県にも近く、駅周辺や出張買取で金製品を売却しやすい地域です。",
  ["morioka-kin-kaitori","sendai-kin-kaitori","kin-takaku-uru"]),
 ("tsuruoka-kin-kaitori","鶴岡","山形県","hokkaido-tohoku","庄内地方の城下町",
  ["鶴岡駅周辺","鶴岡公園周辺","鶴岡市役所周辺"],
  "鶴岡市は庄内地方を代表する城下町です。郊外店舗や出張買取が中心で、庄内一帯の金製品売却に対応しています。",
  ["yamagata-kin-kaitori","sendai-kin-kaitori","kin-kaitori-souba"]),
 ("iwaki-kin-kaitori","いわき","福島県","hokkaido-tohoku","浜通り最大の都市",
  ["いわき駅周辺","平","小名浜方面"],
  "いわき市は太平洋に面した福島県浜通り最大の都市です。広い市域に郊外店舗が点在し、出張買取で金製品を売却しやすい地域です。",
  ["koriyama-kin-kaitori","fukushima-kin-kaitori","kin-takaku-uru"]),
]

def main():
    meta = json.load(open(META, encoding="utf-8"))
    existing = {m["slug"] for m in meta}
    added = []
    for slug, city, pref, region, hook, districts, intro, related in AREAS2:
        if slug in existing:
            print("skip exists:", slug); continue
        d = os.path.join(ART, slug); os.makedirs(d, exist_ok=True)
        open(os.path.join(d, "page.tsx"), "w", encoding="utf-8").write(
            gen(slug, city, pref, region, hook, districts, intro, related))
        title = f"{city}の金買取おすすめガイド"
        meta.append({"slug": slug, "title": title, "shortTitle": title,
                     "badge": city, "category": "region",
                     "description": f"{city}の金買取相場・方法・高く売るコツを解説。"})
        added.append(slug)
    json.dump(meta, open(META, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print(f"\nbatch2 generated: {len(added)} / requested {len(AREAS2)}")
    print("metadata total now:", len(meta))

if __name__ == "__main__":
    main()
